### ISSUE TITLE
how to integrate workflowr and confluence wiki?

### ISSUE THREAD

**Issue by harryprince** [jdblischak/workflowrBeta#1]
Building and maintaining a website is so hard for DS, is it possible to connect to confluence wiki instead of Github Page?

**Comment by jdblischak** [comment]
@harryprince Thanks for your interest in workflowr!

> Building and maintaining a website is so hard for DS

Agreed! I designed the workflowr package to make it easier for data scientists to version and share their work without having to worry much about website configuration and deployment.

> is it possible to connect to confluence wiki instead of Github Page?

Potentially. The question is whether to solve the problem with documentation only or if some of the steps can be automated.

Some follow-up questions for you:

1. Do you have projects that rely on workflowrBeta? I maintain this repo for legacy projects that were built with the beta version of workflowr. The latest development is happening in the official [workflowr repo](https://github.com/jdblischak/workflowr) (which is what ends up being released to [CRAN](https://cran.r-project.org/package=workflowr)).

2. Could you describe how you use the Confluence wiki and send me links to any useful documentation? Do you know if the Confluence wiki will host raw HTML files?

**Comment by harryprince** [comment]
Confluence wiki supports markdown format document, and currently, I should copy-paste my Rmarkdown result into it. It seems Confluence wiki provides some hooks to update the document.

And Confluence wiki is very popular and easy to share knowledge of the inner organization.

**Comment by jdblischak** [comment]
> Confluence wiki supports markdown format document, and currently, I should copy-paste my Rmarkdown result into it.

@harryprince Do you run `knit` from the knitr package or do you run `render` from the rmarkdown package with the output format `md_document`?

> It seems Confluence wiki provides some hooks to update the document.

Could you please send me the relevant links about hooks? It might be possible to create a post-commit hook for a Bitbucket repository to copy the workflowr website to the wiki. I don't have access to Confluence (the wiki is a proprietary product), so I'll need you to investigate.

Could you please contact Atlassian support and ask them if it is possible to upload raw HTML into the Confluence wiki? I tried filling out the support form myself, but it requires that you enter the link to your Confluence wiki.

https://support.atlassian.com/contact/

The final output of workflowr is a version-controlled Bootstrap3 website. If the Confluence wiki doesn't accept raw HTML, then I don't think it will be possible to integrate with workflowr.

**Comment by jdblischak** [comment]
It looks like the R package [conflr](https://cran.r-project.org/package=conflr) could be used to upload Rmd output to Confluence. If anyone is interested in trying this out, please open an [Issue at the workflowr repository](https://github.com/jdblischak/workflowr/issues). Only legacy users should use workflowrBeta for older projects.
